[package]
name = "store"
version = "0.1.1"
description = "Mutable key-value store with optional secondary indexes."
repository = "https://github.com/DATHKA/motoko-store"
keywords = [ "database", "db", "data-structure", "utils"]
license = "MIT"
[dependencies]
core = "1.0.0"
test = "2.1.1"